# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c46ad52503191a18f3900c14d7858d37422a7c891cfcea331b006d72be76eb1df574280e3ca17c32cfb04890aac11ed26b2946abcc4ae98aa22ec5ebd1f6b341

test:
  secret_key_base: 60a74b61efb57a3ef2f5fbfd1ded1e6e7ed61fc3f3a06336b81d56233bf2f0d76f460d64d718b6e6e5f8310e38c9f323709e9b73511c20a48a6841cf2475e06a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
